

// Create Rating
export const CREATE_RATING_REQUEST = 'CREATE_RATING_REQUEST';
export const CREATE_RATING_SUCCESS = 'CREATE_RATING_SUCCESS';
export const CREATE_RATING_FAILURE = 'CREATE_RATING_FAILURE';

// Get All Ratings
export const GET_ALL_RATINGS_REQUEST = 'GET_ALL_RATINGS_REQUEST';
export const GET_ALL_RATINGS_SUCCESS = 'GET_ALL_RATINGS_SUCCESS';
export const GET_ALL_RATINGS_FAILURE = 'GET_ALL_RATINGS_FAILURE';

// Get  Rating By Id
export const GET_RATING_BY_ID_REQUEST = 'GET_RATING_BY_ID_REQUEST';
export const GET_RATING_BY_ID_SUCCESS = 'GET_RATING_BY_ID_SUCCESS';
export const GET_RATING_BY_ID_FAILURE = 'GET_RATING_BY_ID_FAILURE';


// Update Rating
export const UPDATE_RATING_REQUEST = 'UPDATE_RATING_REQUEST';
export const UPDATE_RATING_SUCCESS = 'UPDATE_RATING_SUCCESS';
export const UPDATE_RATING_FAILURE = 'UPDATE_RATING_FAILURE';