export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE"

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST"
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS"
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE"

export const GET_ORDER_HISTORY_REQUEST = "GET_ORDER_HISTORY_REQUEST"
export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS"
export const GET_ORDER_HISTORY_FAILURE = "GET_ORDER_HISTORY_FAILURE"

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";

export const DELETE_ORDER = 'DELETE_ORDER';